/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.Equipo;
import modelo.TipoEquipo;
import modelo.Usuario;
import modelo.Utilidades;

/**
 *
 * @author Usuario
 */
public class gestionEquipo extends javax.swing.JInternalFrame {

    private ControladoraPrincipal cp;
    private JDesktopPane dskp_principalVP;
    private Usuario usuario;

    /**
     * Creates new form gestionEquipo
     */
    public gestionEquipo(ControladoraPrincipal cp, Usuario usuario, JDesktopPane dskp_principalVP) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.cp = cp;
        this.usuario = usuario;
        this.dskp_principalVP = dskp_principalVP;
        this.estadoInicial();
    }

    public void estadoInicial() {

        cargarTabla(this.cp.getControladoraServicioTecnico().listarEquipo());
        Utilidades.cargarCombo(this.cp.getControladoraServicioTecnico().listarTipoEquipo(), cmb_tipoEquipoGE);

        tb_listadoEquipoGE.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));

        btn_nuevoGE.setEnabled(isEnabled());
        btn_editarGE.setEnabled(isEnabled());
        btn_cancelarGE.setEnabled(!isEnabled());
        btn_guardarGE.setEnabled(!isEnabled());
        btn_salirGE.setEnabled(isEnabled());

        txt_codigoGE.setEnabled(!isEnabled());
        txt_modeloGE.setEnabled(!isEnabled());
        txtA_descripcionGE.setEnabled(!isEnabled());
        cmb_tipoEquipoGE.setEnabled(!isEnabled());

        txt_buscarEquipoPorNombreGE.setText("");
        txt_codigoGE.setText("");
        txt_modeloGE.setText("");
        txtA_descripcionGE.setText("");
        
        UIManager.put("ComboBox.disabledBackground", new Color(212, 212, 210));
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);

    }

    public void cambiarEstado() {
        btn_nuevoGE.setEnabled(!isEnabled());
        btn_editarGE.setEnabled(!isEnabled());
        btn_cancelarGE.setEnabled(isEnabled());
        btn_guardarGE.setEnabled(isEnabled());

        txt_codigoGE.setEnabled(!isEnabled());
        txt_modeloGE.setEnabled(isEnabled());
        txtA_descripcionGE.setEnabled(isEnabled());
        cmb_tipoEquipoGE.setEnabled(isEnabled());

    }

    public void cargarTabla(List<Equipo> equipos) {
        DefaultTableModel tbCarga = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };

        if (!equipos.isEmpty()) {
            String Cabecera[] = {"Codigo", "Modelo", "Descripcion", "TipoEquipo"};
            tbCarga.setColumnIdentifiers(Cabecera);
            tb_listadoEquipoGE.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));
            Object fila[] = new Object[tbCarga.getColumnCount()];
            for (Equipo e : equipos) {
                fila[0] = e.getCodigo();
                fila[1] = e.getModelo();
                fila[2] = e.getDescripcion();
                fila[3] = e.getTipoEquipo();

                tbCarga.addRow(fila);

            }

        }
        tb_listadoEquipoGE.setModel(tbCarga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_pieGE = new javax.swing.JPanel();
        btn_nuevoGE = new javax.swing.JButton();
        btn_editarGE = new javax.swing.JButton();
        btn_cancelarGE = new javax.swing.JButton();
        btn_guardarGE = new javax.swing.JButton();
        btn_salirGE = new javax.swing.JButton();
        pnl_encabezadoGE = new javax.swing.JPanel();
        lbl_tituloGE = new javax.swing.JLabel();
        pnl_izquierdoGE = new javax.swing.JPanel();
        pnl_derechoGE = new javax.swing.JPanel();
        pnl_centralGE = new javax.swing.JPanel();
        pnl_GestionEquipoGE = new javax.swing.JPanel();
        pnl_datosEquipoGE = new javax.swing.JPanel();
        lbl_codigoGE = new javax.swing.JLabel();
        txt_codigoGE = new javax.swing.JTextField();
        lbl_modeloGE = new javax.swing.JLabel();
        txt_modeloGE = new javax.swing.JTextField();
        lbl_tipoEquipoGE = new javax.swing.JLabel();
        cmb_tipoEquipoGE = new javax.swing.JComboBox();
        pnl_datosEquipo1GE = new javax.swing.JPanel();
        lbl_decripcionGE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA_descripcionGE = new javax.swing.JTextArea();
        pnl_listadoEquipoGE = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listadoEquipoGE = new javax.swing.JTable();
        pnl_busquedaEquipoGE = new javax.swing.JPanel();
        lbl_buscarEquipoPorNombreGE = new javax.swing.JLabel();
        txt_buscarEquipoPorNombreGE = new javax.swing.JTextField();

        setBorder(null);

        pnl_pieGE.setPreferredSize(new java.awt.Dimension(762, 50));

        btn_nuevoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nuevoGE.setText("Nuevo");
        btn_nuevoGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGEActionPerformed(evt);
            }
        });
        pnl_pieGE.add(btn_nuevoGE);

        btn_editarGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_editarGE.setText("Editar");
        btn_editarGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarGEActionPerformed(evt);
            }
        });
        pnl_pieGE.add(btn_editarGE);

        btn_cancelarGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarGE.setText("Cancelar");
        btn_cancelarGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarGEActionPerformed(evt);
            }
        });
        pnl_pieGE.add(btn_cancelarGE);

        btn_guardarGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarGE.setText("Guardar");
        btn_guardarGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGEActionPerformed(evt);
            }
        });
        pnl_pieGE.add(btn_guardarGE);

        btn_salirGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_salirGE.setText("Salir");
        btn_salirGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirGEActionPerformed(evt);
            }
        });
        pnl_pieGE.add(btn_salirGE);

        getContentPane().add(pnl_pieGE, java.awt.BorderLayout.PAGE_END);

        pnl_encabezadoGE.setPreferredSize(new java.awt.Dimension(762, 50));
        pnl_encabezadoGE.setLayout(new java.awt.GridLayout(1, 0));

        lbl_tituloGE.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloGE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloGE.setText("Gestion de Equipos");
        pnl_encabezadoGE.add(lbl_tituloGE);

        getContentPane().add(pnl_encabezadoGE, java.awt.BorderLayout.PAGE_START);

        pnl_izquierdoGE.setPreferredSize(new java.awt.Dimension(50, 278));

        javax.swing.GroupLayout pnl_izquierdoGELayout = new javax.swing.GroupLayout(pnl_izquierdoGE);
        pnl_izquierdoGE.setLayout(pnl_izquierdoGELayout);
        pnl_izquierdoGELayout.setHorizontalGroup(
            pnl_izquierdoGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_izquierdoGELayout.setVerticalGroup(
            pnl_izquierdoGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoGE, java.awt.BorderLayout.LINE_START);

        pnl_derechoGE.setPreferredSize(new java.awt.Dimension(50, 278));

        javax.swing.GroupLayout pnl_derechoGELayout = new javax.swing.GroupLayout(pnl_derechoGE);
        pnl_derechoGE.setLayout(pnl_derechoGELayout);
        pnl_derechoGELayout.setHorizontalGroup(
            pnl_derechoGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_derechoGELayout.setVerticalGroup(
            pnl_derechoGELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoGE, java.awt.BorderLayout.LINE_END);

        pnl_centralGE.setLayout(new java.awt.BorderLayout());

        pnl_GestionEquipoGE.setLayout(new java.awt.GridLayout(2, 0));

        lbl_codigoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoGE.setText("Codigo:");
        pnl_datosEquipoGE.add(lbl_codigoGE);

        txt_codigoGE.setColumns(5);
        txt_codigoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_datosEquipoGE.add(txt_codigoGE);

        lbl_modeloGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_modeloGE.setText("Modelo:");
        pnl_datosEquipoGE.add(lbl_modeloGE);

        txt_modeloGE.setColumns(15);
        txt_modeloGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_datosEquipoGE.add(txt_modeloGE);

        lbl_tipoEquipoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_tipoEquipoGE.setText("Tipo Equipo:");
        pnl_datosEquipoGE.add(lbl_tipoEquipoGE);

        cmb_tipoEquipoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_tipoEquipoGE.setPreferredSize(new java.awt.Dimension(140, 25));
        pnl_datosEquipoGE.add(cmb_tipoEquipoGE);

        pnl_GestionEquipoGE.add(pnl_datosEquipoGE);

        lbl_decripcionGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_decripcionGE.setText("Descripcion:");
        pnl_datosEquipo1GE.add(lbl_decripcionGE);

        txtA_descripcionGE.setColumns(40);
        txtA_descripcionGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtA_descripcionGE.setRows(4);
        jScrollPane2.setViewportView(txtA_descripcionGE);

        pnl_datosEquipo1GE.add(jScrollPane2);

        pnl_GestionEquipoGE.add(pnl_datosEquipo1GE);

        pnl_centralGE.add(pnl_GestionEquipoGE, java.awt.BorderLayout.PAGE_END);

        pnl_listadoEquipoGE.setLayout(new java.awt.BorderLayout());

        tb_listadoEquipoGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tb_listadoEquipoGE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_listadoEquipoGE);

        pnl_listadoEquipoGE.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_busquedaEquipoGE.setPreferredSize(new java.awt.Dimension(917, 50));

        lbl_buscarEquipoPorNombreGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscarEquipoPorNombreGE.setText("Buscar equipo por modelo: ");
        pnl_busquedaEquipoGE.add(lbl_buscarEquipoPorNombreGE);

        txt_buscarEquipoPorNombreGE.setColumns(10);
        txt_buscarEquipoPorNombreGE.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_buscarEquipoPorNombreGE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarEquipoPorNombreGEKeyReleased(evt);
            }
        });
        pnl_busquedaEquipoGE.add(txt_buscarEquipoPorNombreGE);

        pnl_listadoEquipoGE.add(pnl_busquedaEquipoGE, java.awt.BorderLayout.PAGE_START);

        pnl_centralGE.add(pnl_listadoEquipoGE, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_centralGE, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarGEActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_btn_cancelarGEActionPerformed

    private void btn_nuevoGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGEActionPerformed
        this.cambiarEstado();
    }//GEN-LAST:event_btn_nuevoGEActionPerformed

    private void btn_salirGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirGEActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirGEActionPerformed

    private void btn_guardarGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGEActionPerformed
        try {

            if (!txt_modeloGE.getText().trim().isEmpty() && !txtA_descripcionGE.getText().trim().isEmpty()
                    && cmb_tipoEquipoGE.getSelectedItem() != null && cmb_tipoEquipoGE.getSelectedItem() != "[SELECCIONAR]") {

                TipoEquipo tipoEquipo = (TipoEquipo) cmb_tipoEquipoGE.getSelectedItem();
                String modelo = txt_modeloGE.getText().trim();
                String descripcion = txtA_descripcionGE.getText().trim();

                if (txt_codigoGE.getText().trim().isEmpty()) {
                    Equipo equipo = new Equipo(modelo, descripcion, tipoEquipo);
                    this.cp.getControladoraServicioTecnico().registrarEquipo(equipo);
                    JOptionPane.showMessageDialog(null, "Se creo con Exito", "Gestion de Equipo", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    Integer codigo = Integer.valueOf(txt_codigoGE.getText().trim());
                    Equipo equipo = this.cp.getControladoraServicioTecnico().buscarEquipoPorCodigo(codigo);
                    
                    equipo.setDescripcion(descripcion);
                    equipo.setModelo(modelo);
                    equipo.setTipoEquipo(tipoEquipo);
                    
                    
                    this.cp.getControladoraServicioTecnico().modificarEquipo(equipo);
                    JOptionPane.showMessageDialog(null, "Se edito con Exito", "Gestion de Equipo", JOptionPane.INFORMATION_MESSAGE);
                }

            } else {
                throw new Exception("Todos los campos son obligatorios");

            }

            this.estadoInicial();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gestion de Equipo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarGEActionPerformed

    private void btn_editarGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarGEActionPerformed

        if (tb_listadoEquipoGE.getSelectedRow() > -1 && tb_listadoEquipoGE.getSelectedRowCount() == 1) {
            Integer seleccionado = (Integer) tb_listadoEquipoGE.getValueAt(tb_listadoEquipoGE.getSelectedRow(), 0);
            Equipo equipoSeleccionado = this.cp.getControladoraServicioTecnico().buscarEquipoPorCodigo(seleccionado);

            if (equipoSeleccionado != null) {
                this.cambiarEstado();

                txt_codigoGE.setText(String.valueOf(equipoSeleccionado.getCodigo()));
                txt_modeloGE.setText(equipoSeleccionado.getModelo());
                txtA_descripcionGE.setText(equipoSeleccionado.getDescripcion());
                cmb_tipoEquipoGE.setSelectedItem(equipoSeleccionado.getTipoEquipo());
            }

            tb_listadoEquipoGE.clearSelection();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un equpo", "Gestion de Equipos", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btn_editarGEActionPerformed

    private void txt_buscarEquipoPorNombreGEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarEquipoPorNombreGEKeyReleased
        if(!txt_buscarEquipoPorNombreGE.getText().trim().isEmpty()){
            String nombre= txt_buscarEquipoPorNombreGE.getText().trim();
            cargarTabla(this.cp.getControladoraServicioTecnico().filtrarEquipoPorNombre(nombre));
        }else{
            cargarTabla(this.cp.getControladoraServicioTecnico().listarEquipo());
        }
    }//GEN-LAST:event_txt_buscarEquipoPorNombreGEKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarGE;
    private javax.swing.JButton btn_editarGE;
    private javax.swing.JButton btn_guardarGE;
    private javax.swing.JButton btn_nuevoGE;
    private javax.swing.JButton btn_salirGE;
    private javax.swing.JComboBox cmb_tipoEquipoGE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_buscarEquipoPorNombreGE;
    private javax.swing.JLabel lbl_codigoGE;
    private javax.swing.JLabel lbl_decripcionGE;
    private javax.swing.JLabel lbl_modeloGE;
    private javax.swing.JLabel lbl_tipoEquipoGE;
    private javax.swing.JLabel lbl_tituloGE;
    private javax.swing.JPanel pnl_GestionEquipoGE;
    private javax.swing.JPanel pnl_busquedaEquipoGE;
    private javax.swing.JPanel pnl_centralGE;
    private javax.swing.JPanel pnl_datosEquipo1GE;
    private javax.swing.JPanel pnl_datosEquipoGE;
    private javax.swing.JPanel pnl_derechoGE;
    private javax.swing.JPanel pnl_encabezadoGE;
    private javax.swing.JPanel pnl_izquierdoGE;
    private javax.swing.JPanel pnl_listadoEquipoGE;
    private javax.swing.JPanel pnl_pieGE;
    private javax.swing.JTable tb_listadoEquipoGE;
    private javax.swing.JTextArea txtA_descripcionGE;
    private javax.swing.JTextField txt_buscarEquipoPorNombreGE;
    private javax.swing.JTextField txt_codigoGE;
    private javax.swing.JTextField txt_modeloGE;
    // End of variables declaration//GEN-END:variables
}
