/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Provincia;
import modelo.Usuario;
import modelo.Utilidades;


/**
 *
 * @author EcobarM
 */
public class gestionProvincias extends javax.swing.JInternalFrame {

    private ControladoraPrincipal cp;
    private JDesktopPane dskp_principalVP;
    private Usuario usuario;

    /**
     * Creates new form gestionProvincias
     */
    public gestionProvincias(ControladoraPrincipal cp, JDesktopPane dskp_principalVP, Usuario usuario) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.cp = cp;
        this.usuario = usuario;
        this.dskp_principalVP = dskp_principalVP;
        this.estadoInicial();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_encabezadoGP = new javax.swing.JPanel();
        lbl_tituloGP = new javax.swing.JLabel();
        pnl_derechoGP = new javax.swing.JPanel();
        pnl_pieGP = new javax.swing.JPanel();
        btn_nuevoGP = new javax.swing.JButton();
        btn_editarGP = new javax.swing.JButton();
        btn_cancelarGP = new javax.swing.JButton();
        btn_guardarGP = new javax.swing.JButton();
        btn_salirGP = new javax.swing.JButton();
        pnl_izquierdoGP = new javax.swing.JPanel();
        pnl_centralGP = new javax.swing.JPanel();
        pnl_formularioCentralGP = new javax.swing.JPanel();
        lbl_codigoGP = new javax.swing.JLabel();
        txt_codigoGP = new javax.swing.JTextField();
        lbl_nombreGP = new javax.swing.JLabel();
        txt_nombreGP = new javax.swing.JTextField();
        pnl_encabezadoCentralGP = new javax.swing.JPanel();
        lbl_buscarPorProvinciaGP = new javax.swing.JLabel();
        txt_buscarPorProvinciaGP = new javax.swing.JTextField();
        pnl_listadoCentralGP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listadoProvinciasGP = new javax.swing.JTable();
        pnl_derechoCentralGL = new javax.swing.JPanel();
        pnl_izquierdoCentralGL = new javax.swing.JPanel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Provincias");

        pnl_encabezadoGP.setPreferredSize(new java.awt.Dimension(673, 50));
        pnl_encabezadoGP.setLayout(new java.awt.BorderLayout());

        lbl_tituloGP.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloGP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloGP.setText("Gestion de Provincias");
        pnl_encabezadoGP.add(lbl_tituloGP, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_encabezadoGP, java.awt.BorderLayout.NORTH);

        pnl_derechoGP.setPreferredSize(new java.awt.Dimension(30, 50));

        javax.swing.GroupLayout pnl_derechoGPLayout = new javax.swing.GroupLayout(pnl_derechoGP);
        pnl_derechoGP.setLayout(pnl_derechoGPLayout);
        pnl_derechoGPLayout.setHorizontalGroup(
            pnl_derechoGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnl_derechoGPLayout.setVerticalGroup(
            pnl_derechoGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoGP, java.awt.BorderLayout.EAST);

        pnl_pieGP.setPreferredSize(new java.awt.Dimension(673, 50));
        pnl_pieGP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15));

        btn_nuevoGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nuevoGP.setText("Nuevo");
        btn_nuevoGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGPActionPerformed(evt);
            }
        });
        pnl_pieGP.add(btn_nuevoGP);

        btn_editarGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_editarGP.setText("Editar");
        btn_editarGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarGPActionPerformed(evt);
            }
        });
        pnl_pieGP.add(btn_editarGP);

        btn_cancelarGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarGP.setText("Cancelar");
        btn_cancelarGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarGPActionPerformed(evt);
            }
        });
        pnl_pieGP.add(btn_cancelarGP);

        btn_guardarGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarGP.setText("Guardar");
        btn_guardarGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGPActionPerformed(evt);
            }
        });
        pnl_pieGP.add(btn_guardarGP);

        btn_salirGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_salirGP.setText("Salir");
        btn_salirGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirGPActionPerformed(evt);
            }
        });
        pnl_pieGP.add(btn_salirGP);

        getContentPane().add(pnl_pieGP, java.awt.BorderLayout.SOUTH);

        pnl_izquierdoGP.setPreferredSize(new java.awt.Dimension(30, 160));

        javax.swing.GroupLayout pnl_izquierdoGPLayout = new javax.swing.GroupLayout(pnl_izquierdoGP);
        pnl_izquierdoGP.setLayout(pnl_izquierdoGPLayout);
        pnl_izquierdoGPLayout.setHorizontalGroup(
            pnl_izquierdoGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        pnl_izquierdoGPLayout.setVerticalGroup(
            pnl_izquierdoGPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoGP, java.awt.BorderLayout.WEST);

        pnl_centralGP.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 30);
        flowLayout1.setAlignOnBaseline(true);
        pnl_formularioCentralGP.setLayout(flowLayout1);

        lbl_codigoGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoGP.setText("Codigo: ");
        pnl_formularioCentralGP.add(lbl_codigoGP);

        txt_codigoGP.setColumns(2);
        txt_codigoGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioCentralGP.add(txt_codigoGP);

        lbl_nombreGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreGP.setText("Nombre: ");
        pnl_formularioCentralGP.add(lbl_nombreGP);

        txt_nombreGP.setColumns(10);
        txt_nombreGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioCentralGP.add(txt_nombreGP);

        pnl_centralGP.add(pnl_formularioCentralGP, java.awt.BorderLayout.SOUTH);

        pnl_encabezadoCentralGP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lbl_buscarPorProvinciaGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscarPorProvinciaGP.setText("Buscar  por Provincia: ");
        pnl_encabezadoCentralGP.add(lbl_buscarPorProvinciaGP);

        txt_buscarPorProvinciaGP.setColumns(10);
        txt_buscarPorProvinciaGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_buscarPorProvinciaGP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarPorProvinciaGPKeyReleased(evt);
            }
        });
        pnl_encabezadoCentralGP.add(txt_buscarPorProvinciaGP);

        pnl_centralGP.add(pnl_encabezadoCentralGP, java.awt.BorderLayout.NORTH);

        pnl_listadoCentralGP.setLayout(new java.awt.GridLayout(1, 0));

        tb_listadoProvinciasGP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tb_listadoProvinciasGP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_listadoProvinciasGP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listadoProvinciasGPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listadoProvinciasGP);

        pnl_listadoCentralGP.add(jScrollPane1);

        pnl_centralGP.add(pnl_listadoCentralGP, java.awt.BorderLayout.CENTER);

        pnl_derechoCentralGL.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout pnl_derechoCentralGLLayout = new javax.swing.GroupLayout(pnl_derechoCentralGL);
        pnl_derechoCentralGL.setLayout(pnl_derechoCentralGLLayout);
        pnl_derechoCentralGLLayout.setHorizontalGroup(
            pnl_derechoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnl_derechoCentralGLLayout.setVerticalGroup(
            pnl_derechoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pnl_centralGP.add(pnl_derechoCentralGL, java.awt.BorderLayout.EAST);

        pnl_izquierdoCentralGL.setPreferredSize(new java.awt.Dimension(150, 479));

        javax.swing.GroupLayout pnl_izquierdoCentralGLLayout = new javax.swing.GroupLayout(pnl_izquierdoCentralGL);
        pnl_izquierdoCentralGL.setLayout(pnl_izquierdoCentralGLLayout);
        pnl_izquierdoCentralGLLayout.setHorizontalGroup(
            pnl_izquierdoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnl_izquierdoCentralGLLayout.setVerticalGroup(
            pnl_izquierdoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        pnl_centralGP.add(pnl_izquierdoCentralGL, java.awt.BorderLayout.WEST);

        getContentPane().add(pnl_centralGP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGPActionPerformed

        try {
            if (!txt_nombreGP.getText().trim().isEmpty()) {
                String nombre = txt_nombreGP.getText().trim();
                if (txt_codigoGP.getText().trim().isEmpty()) {
                    Provincia provincia = new Provincia(nombre);
                    this.cp.getControladoraCliente().registrarProvincia(provincia);

                    JOptionPane.showMessageDialog(null, "Creado con Exito", "Gestion de Provincias", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    int codigo = Integer.valueOf(txt_codigoGP.getText());
                    Provincia provincia = this.cp.getControladoraCliente().buscarProvinciaPorCodigo(codigo);
                    provincia.setNombre(nombre);

                    this.cp.getControladoraCliente().modificarProvincia(provincia);
                    JOptionPane.showMessageDialog(null, "Editado con Exito", "Gestion de Provincias", JOptionPane.INFORMATION_MESSAGE);

                }
                this.estadoInicial();

            } else {

                throw new Exception("Todos los campos son obligatorios");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gestion de Provincias", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btn_guardarGPActionPerformed

    private void btn_nuevoGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGPActionPerformed
        this.cambiarEstado();
        tb_listadoProvinciasGP.clearSelection();
    }//GEN-LAST:event_btn_nuevoGPActionPerformed

    private void btn_salirGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirGPActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirGPActionPerformed

    private void btn_editarGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarGPActionPerformed
        if (tb_listadoProvinciasGP.getSelectedRow() > -1 && tb_listadoProvinciasGP.getSelectedRowCount() == 1) {

            Integer seleccionado = (Integer) tb_listadoProvinciasGP.getValueAt(tb_listadoProvinciasGP.getSelectedRow(), 0);
            Provincia provinciaSeleccionado = this.cp.getControladoraCliente().buscarProvinciaPorCodigo(seleccionado);

            if (provinciaSeleccionado != null) {
                txt_codigoGP.setText(String.valueOf(provinciaSeleccionado.getCodigo()));
                txt_nombreGP.setText(provinciaSeleccionado.getNombre());

                this.cambiarEstado();
            }

            
            tb_listadoProvinciasGP.clearSelection();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un provincia", "Gestion de Provincias", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_editarGPActionPerformed

    private void tb_listadoProvinciasGPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listadoProvinciasGPMouseClicked

    }//GEN-LAST:event_tb_listadoProvinciasGPMouseClicked

    private void btn_cancelarGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarGPActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_btn_cancelarGPActionPerformed

    private void txt_buscarPorProvinciaGPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarPorProvinciaGPKeyReleased
        if (!txt_buscarPorProvinciaGP.getText().trim().isEmpty()) {
            String nombre = txt_buscarPorProvinciaGP.getText().trim();
            cargarTabla(this.cp.getControladoraCliente().filtrarProvinciaPorNombre(nombre));
        } else {
            cargarTabla(this.cp.getControladoraCliente().listarProvincias());
        }
    }//GEN-LAST:event_txt_buscarPorProvinciaGPKeyReleased

    public void cargarTabla(List<Provincia> provincias) {
        DefaultTableModel tbCarga = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (!provincias.isEmpty()) {
            String Cabecera[] = {"Codigo", "Nombre"};
            tbCarga.setColumnIdentifiers(Cabecera);
            Object fila[] = new Object[tbCarga.getColumnCount()];
            tb_listadoProvinciasGP.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));
            for (Provincia p : provincias) {
                fila[0] = p.getCodigo();
                fila[1] = p.getNombre();
                tbCarga.addRow(fila);
            }
           
        }
         tb_listadoProvinciasGP.setModel(tbCarga);
    }

    public void estadoInicial() {
        btn_nuevoGP.setEnabled(isEnabled());
        btn_editarGP.setEnabled(isEnabled());
        btn_cancelarGP.setEnabled(!isEnabled());
        btn_guardarGP.setEnabled(!isEnabled());
        btn_salirGP.setEnabled(isEnabled());

        txt_codigoGP.setEnabled(!isEnabled());
        txt_codigoGP.setDisabledTextColor(Color.BLACK);
        txt_nombreGP.setDisabledTextColor(Color.BLACK);
        
        txt_buscarPorProvinciaGP.setEnabled(isEnabled());
        txt_buscarPorProvinciaGP.setText("");
        
        tb_listadoProvinciasGP.setEnabled(isEnabled());

        txt_codigoGP.setText("");
        txt_nombreGP.setText("");

        txt_nombreGP.setEnabled(!isEnabled());

        txt_nombreGP.setBackground(Color.WHITE);
        txt_codigoGP.setBackground(Color.WHITE);

        cargarTabla(this.cp.getControladoraCliente().listarProvincias());

    }

    public void cambiarEstado() {
        

        tb_listadoProvinciasGP.setEnabled(!isEnabled());
        
        btn_nuevoGP.setEnabled(!isEnabled());
        btn_editarGP.setEnabled(!isEnabled());
        btn_cancelarGP.setEnabled(isEnabled());
        btn_guardarGP.setEnabled(isEnabled());
        btn_salirGP.setEnabled(isEnabled());

        txt_nombreGP.setEnabled(isEnabled());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarGP;
    private javax.swing.JButton btn_editarGP;
    private javax.swing.JButton btn_guardarGP;
    private javax.swing.JButton btn_nuevoGP;
    private javax.swing.JButton btn_salirGP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscarPorProvinciaGP;
    private javax.swing.JLabel lbl_codigoGP;
    private javax.swing.JLabel lbl_nombreGP;
    private javax.swing.JLabel lbl_tituloGP;
    private javax.swing.JPanel pnl_centralGP;
    private javax.swing.JPanel pnl_derechoCentralGL;
    private javax.swing.JPanel pnl_derechoGP;
    private javax.swing.JPanel pnl_encabezadoCentralGP;
    private javax.swing.JPanel pnl_encabezadoGP;
    private javax.swing.JPanel pnl_formularioCentralGP;
    private javax.swing.JPanel pnl_izquierdoCentralGL;
    private javax.swing.JPanel pnl_izquierdoGP;
    private javax.swing.JPanel pnl_listadoCentralGP;
    private javax.swing.JPanel pnl_pieGP;
    private javax.swing.JTable tb_listadoProvinciasGP;
    private javax.swing.JTextField txt_buscarPorProvinciaGP;
    private javax.swing.JTextField txt_codigoGP;
    private javax.swing.JTextField txt_nombreGP;
    // End of variables declaration//GEN-END:variables
}
