/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.TipoProducto;
import modelo.Usuario;
import modelo.Utilidades;

/**
 *
 * @author EcobarM
 */
public class gestionTipoProducto extends javax.swing.JInternalFrame {

    private ControladoraPrincipal cp;
    private JDesktopPane dskp_principalVP;
    private Usuario usuario;

    /**
     * Creates new form gestionTipoProducto
     */
    public gestionTipoProducto(ControladoraPrincipal cp, Usuario usuario, JDesktopPane dskp_principalVP) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.cp = cp;
        this.usuario = usuario;
        this.dskp_principalVP = dskp_principalVP;
        this.estadoInicial();
    }

    public void estadoInicial() {

        cargarTabla(this.cp.getControladoraProducto().listarTipoProductos());

        tb_listadoTipoProductoGTP.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));
        tb_listadoTipoProductoGTP.setEnabled(isEnabled());
        
        txt_codigoGTP.setEnabled(!isEnabled());
        txt_nombreGTP.setEnabled(!isEnabled());
        
        btn_cancelarGTP.setEnabled(!isEnabled());
        btn_guardarGTP.setEnabled(!isEnabled());
        btn_salirGTP.setEnabled(isEnabled());
        btn_nuevoGTP.setEnabled(isEnabled());
        btn_editarGTP.setEnabled(isEnabled());

        txt_buscarPorNombreGTP.setEnabled(isEnabled());

        txt_buscarPorNombreGTP.setText("");
        
        txt_codigoGTP.setText("");
        txt_nombreGTP.setText("");

    }

    public void cambiarEstado() {

        tb_listadoTipoProductoGTP.setEnabled(!isEnabled());
        txt_codigoGTP.setEnabled(!isEnabled());
        txt_nombreGTP.setEnabled(isEnabled());
        btn_cancelarGTP.setEnabled(isEnabled());
        btn_guardarGTP.setEnabled(isEnabled());
        btn_nuevoGTP.setEnabled(!isEnabled());
        btn_editarGTP.setEnabled(!isEnabled());

    }

    public void cargarTabla(List<TipoProducto> TipoProducto) {
        DefaultTableModel tbCarga = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (!TipoProducto.isEmpty()) {
            String Cabecera[] = {"Codigo", "Nombre"};
            tbCarga.setColumnIdentifiers(Cabecera);
            Object fila[] = new Object[tbCarga.getColumnCount()];
            for (TipoProducto Tp : TipoProducto) {
                fila[0] = Tp.getCodigo();
                fila[1] = Tp.getNombre();
                tbCarga.addRow(fila);
            }

        }
        tb_listadoTipoProductoGTP.setModel(tbCarga);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_encabezadoGTP = new javax.swing.JPanel();
        lbl_tituloGTP = new javax.swing.JLabel();
        pnl_pieGTP = new javax.swing.JPanel();
        btn_nuevoGTP = new javax.swing.JButton();
        btn_editarGTP = new javax.swing.JButton();
        btn_cancelarGTP = new javax.swing.JButton();
        btn_guardarGTP = new javax.swing.JButton();
        btn_salirGTP = new javax.swing.JButton();
        pnl_izquierdoGTP = new javax.swing.JPanel();
        pnl_derechoGTP = new javax.swing.JPanel();
        pnl_centralGTP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listadoTipoProductoGTP = new javax.swing.JTable();
        pnl_encabezadoCentralGTP = new javax.swing.JPanel();
        lbl_buscarPorNombreGTP = new javax.swing.JLabel();
        txt_buscarPorNombreGTP = new javax.swing.JTextField();
        pnl_formularioGTP = new javax.swing.JPanel();
        lbl_codigoGTP = new javax.swing.JLabel();
        txt_codigoGTP = new javax.swing.JTextField();
        lbl_nombreGTP = new javax.swing.JLabel();
        txt_nombreGTP = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Tipos Producto");

        pnl_encabezadoGTP.setPreferredSize(new java.awt.Dimension(661, 50));
        pnl_encabezadoGTP.setLayout(new java.awt.BorderLayout());

        lbl_tituloGTP.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloGTP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloGTP.setText("Gestion de Tipos de Producto");
        pnl_encabezadoGTP.add(lbl_tituloGTP, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_encabezadoGTP, java.awt.BorderLayout.PAGE_START);

        pnl_pieGTP.setPreferredSize(new java.awt.Dimension(661, 50));
        pnl_pieGTP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btn_nuevoGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nuevoGTP.setText("Nuevo");
        btn_nuevoGTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGTPActionPerformed(evt);
            }
        });
        pnl_pieGTP.add(btn_nuevoGTP);

        btn_editarGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_editarGTP.setText("Editar");
        btn_editarGTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarGTPActionPerformed(evt);
            }
        });
        pnl_pieGTP.add(btn_editarGTP);

        btn_cancelarGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarGTP.setText("Cancelar");
        btn_cancelarGTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarGTPActionPerformed(evt);
            }
        });
        pnl_pieGTP.add(btn_cancelarGTP);

        btn_guardarGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarGTP.setText("Guardar");
        btn_guardarGTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGTPActionPerformed(evt);
            }
        });
        pnl_pieGTP.add(btn_guardarGTP);

        btn_salirGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_salirGTP.setText("Salir");
        btn_salirGTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirGTPActionPerformed(evt);
            }
        });
        pnl_pieGTP.add(btn_salirGTP);

        getContentPane().add(pnl_pieGTP, java.awt.BorderLayout.PAGE_END);

        pnl_izquierdoGTP.setPreferredSize(new java.awt.Dimension(150, 224));

        javax.swing.GroupLayout pnl_izquierdoGTPLayout = new javax.swing.GroupLayout(pnl_izquierdoGTP);
        pnl_izquierdoGTP.setLayout(pnl_izquierdoGTPLayout);
        pnl_izquierdoGTPLayout.setHorizontalGroup(
            pnl_izquierdoGTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnl_izquierdoGTPLayout.setVerticalGroup(
            pnl_izquierdoGTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoGTP, java.awt.BorderLayout.WEST);

        pnl_derechoGTP.setPreferredSize(new java.awt.Dimension(150, 224));

        javax.swing.GroupLayout pnl_derechoGTPLayout = new javax.swing.GroupLayout(pnl_derechoGTP);
        pnl_derechoGTP.setLayout(pnl_derechoGTPLayout);
        pnl_derechoGTPLayout.setHorizontalGroup(
            pnl_derechoGTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        pnl_derechoGTPLayout.setVerticalGroup(
            pnl_derechoGTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoGTP, java.awt.BorderLayout.EAST);

        pnl_centralGTP.setLayout(new java.awt.BorderLayout());

        tb_listadoTipoProductoGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tb_listadoTipoProductoGTP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_listadoTipoProductoGTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listadoTipoProductoGTPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listadoTipoProductoGTP);

        pnl_centralGTP.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnl_encabezadoCentralGTP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lbl_buscarPorNombreGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscarPorNombreGTP.setText("Buscar por nombre: ");
        pnl_encabezadoCentralGTP.add(lbl_buscarPorNombreGTP);

        txt_buscarPorNombreGTP.setColumns(10);
        txt_buscarPorNombreGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_buscarPorNombreGTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarPorNombreGTPKeyReleased(evt);
            }
        });
        pnl_encabezadoCentralGTP.add(txt_buscarPorNombreGTP);

        pnl_centralGTP.add(pnl_encabezadoCentralGTP, java.awt.BorderLayout.NORTH);

        pnl_formularioGTP.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 5));

        lbl_codigoGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoGTP.setText("Codigo: ");
        pnl_formularioGTP.add(lbl_codigoGTP);

        txt_codigoGTP.setColumns(2);
        txt_codigoGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGTP.add(txt_codigoGTP);

        lbl_nombreGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreGTP.setText("Nombre: ");
        pnl_formularioGTP.add(lbl_nombreGTP);

        txt_nombreGTP.setColumns(10);
        txt_nombreGTP.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGTP.add(txt_nombreGTP);

        pnl_centralGTP.add(pnl_formularioGTP, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnl_centralGTP, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarGTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGTPActionPerformed
        try {
            if (!txt_nombreGTP.getText().trim().isEmpty()) {
                String nombre = txt_nombreGTP.getText().trim();

                if (txt_codigoGTP.getText().trim().isEmpty()) {
                    TipoProducto tipoProducto = new TipoProducto(nombre);
                    this.cp.getControladoraProducto().RegistarTipoProducto(tipoProducto);
                    JOptionPane.showMessageDialog(null, "Creado con Exito", "Gestion de Tipo Producto", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    Integer codigo = Integer.valueOf(txt_codigoGTP.getText().trim());
                    TipoProducto tipoProducto = this.cp.getControladoraProducto().buscarTipoProductoPorCodigo(codigo);
                    tipoProducto.setNombre(nombre);

                    this.cp.getControladoraProducto().ModificarTipoProducto(tipoProducto);
                    JOptionPane.showMessageDialog(null, "Editado con Exito", "Gestion de Tipo Producto", JOptionPane.INFORMATION_MESSAGE);
                }
                this.estadoInicial();

            } else {
                throw new Exception("Todos los campos son obligatorios");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gestion de Tipo de Producto", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btn_guardarGTPActionPerformed

    private void btn_nuevoGTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGTPActionPerformed

     this.cambiarEstado();
     tb_listadoTipoProductoGTP.clearSelection();
    }//GEN-LAST:event_btn_nuevoGTPActionPerformed

    private void btn_editarGTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarGTPActionPerformed
        if (tb_listadoTipoProductoGTP.getSelectedRow() > -1 && tb_listadoTipoProductoGTP.getSelectedRowCount() == 1) {
            Integer seleccionado = (Integer) tb_listadoTipoProductoGTP.getValueAt(tb_listadoTipoProductoGTP.getSelectedRow(), 0);
            TipoProducto tipoProductoSeleccionado = this.cp.getControladoraProducto().buscarTipoProductoPorCodigo(seleccionado);
            if (tipoProductoSeleccionado != null) {
                txt_codigoGTP.setText(String.valueOf(tipoProductoSeleccionado.getCodigo()));
                txt_nombreGTP.setText(tipoProductoSeleccionado.getNombre());
            }
            this.cambiarEstado();
            tb_listadoTipoProductoGTP.clearSelection();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un tipo", "Gestion de Tipos de Producto", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btn_editarGTPActionPerformed

    private void btn_cancelarGTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarGTPActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_btn_cancelarGTPActionPerformed

    private void btn_salirGTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirGTPActionPerformed
        this.dispose();

    }//GEN-LAST:event_btn_salirGTPActionPerformed

    private void tb_listadoTipoProductoGTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listadoTipoProductoGTPMouseClicked
    }//GEN-LAST:event_tb_listadoTipoProductoGTPMouseClicked

    private void txt_buscarPorNombreGTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarPorNombreGTPKeyReleased
        if(!txt_buscarPorNombreGTP.getText().trim().isEmpty()){
            String nombre = txt_buscarPorNombreGTP.getText().trim();
            cargarTabla(this.cp.getControladoraProducto().filtrarTipoProductoPorNombre(nombre));
        
        }else{
            cargarTabla(this.cp.getControladoraProducto().listarTipoProductos());
        
        }
    }//GEN-LAST:event_txt_buscarPorNombreGTPKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarGTP;
    private javax.swing.JButton btn_editarGTP;
    private javax.swing.JButton btn_guardarGTP;
    private javax.swing.JButton btn_nuevoGTP;
    private javax.swing.JButton btn_salirGTP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscarPorNombreGTP;
    private javax.swing.JLabel lbl_codigoGTP;
    private javax.swing.JLabel lbl_nombreGTP;
    private javax.swing.JLabel lbl_tituloGTP;
    private javax.swing.JPanel pnl_centralGTP;
    private javax.swing.JPanel pnl_derechoGTP;
    private javax.swing.JPanel pnl_encabezadoCentralGTP;
    private javax.swing.JPanel pnl_encabezadoGTP;
    private javax.swing.JPanel pnl_formularioGTP;
    private javax.swing.JPanel pnl_izquierdoGTP;
    private javax.swing.JPanel pnl_pieGTP;
    private javax.swing.JTable tb_listadoTipoProductoGTP;
    private javax.swing.JTextField txt_buscarPorNombreGTP;
    private javax.swing.JTextField txt_codigoGTP;
    private javax.swing.JTextField txt_nombreGTP;
    // End of variables declaration//GEN-END:variables
}
