/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import modelo.NivelDeUsuario;
import modelo.Usuario;
import modelo.Utilidades;

/**
 *
 * @author EcobarM
 */
public class gestionUsuarios extends javax.swing.JInternalFrame {

    private ControladoraPrincipal cp;
    private Usuario usuario;

    /**
     * Creates new form gestionUsuarios
     */
    public gestionUsuarios(ControladoraPrincipal cp, Usuario usuario) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.cp = cp;
        this.usuario = usuario;

        this.estadoInicial();
    }

    public void cargarTabla(List<Usuario> usuarios) {
        DefaultTableModel tbCarga = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (!usuarios.isEmpty()) {
            String Cabecera[] = {"Codigo", "Apellido", "Nombre", "Usuario", "Nivel", "Registrado Por"};
            tbCarga.setColumnIdentifiers(Cabecera);
            Object fila[] = new Object[tbCarga.getColumnCount()];
            tb_listadoUsuariosGU.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));
            for (Usuario u : usuarios) {
                fila[0] = u.getCodigo();
                fila[1] = u.getApellido();
                fila[2] = u.getNombre();
                fila[3] = u.getNombreUsuario();
                fila[4] = u.getNivel();
                fila[5] = u.getRegistradoPor();
                tbCarga.addRow(fila);
            }
            
        }
        tb_listadoUsuariosGU.setModel(tbCarga);
    }

    public void estadoInicial() {
        txt_apellidoGU.setText("");
        txt_codigoGU.setText("");
        txt_nombreGU.setText("");
        txt_usuarioGU.setText("");
        psw_claveGU.setText("");

        txt_buscarUsuarioPorNombreUsuarioGU.setText("");
        txt_buscarUsuarioPorNombreUsuarioGU.setEnabled(isEnabled());
        
        txt_apellidoGU.setEnabled(!isEnabled());
        txt_codigoGU.setEnabled(!isEnabled());
        txt_nombreGU.setEnabled(!isEnabled());
        txt_usuarioGU.setEnabled(!isEnabled());
        psw_claveGU.setEnabled(!isEnabled());
        cmb_nivelGU.setEnabled(!isEnabled());

        txt_apellidoGU.setDisabledTextColor(Color.BLACK);
        txt_codigoGU.setDisabledTextColor(Color.BLACK);
        txt_nombreGU.setDisabledTextColor(Color.BLACK);
        txt_usuarioGU.setDisabledTextColor(Color.BLACK);
        psw_claveGU.setDisabledTextColor(Color.BLACK);

        cargarTabla(this.cp.getControladoraLogueo().listarUsuario());

        Utilidades.cargarCombo(this.cp.getControladoraLogueo().listarNiveles(), cmb_nivelGU);

        UIManager.put("ComboBox.disabledBackground", new Color(212, 212, 210));
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);

        btn_nuevoGU.setEnabled(isEnabled());
        btn_editarGU.setEnabled(isEnabled());
        btn_cancelarGU.setEnabled(!isEnabled());
        btn_guardarGU.setEnabled(!isEnabled());
        btn_salirGU.setEnabled(isEnabled());

    }

    public void cambiarEstado() {
        
        Utilidades.cargarCombo(this.cp.getControladoraLogueo().listarNiveles(), cmb_nivelGU);
        txt_apellidoGU.setEnabled(isEnabled());
        txt_nombreGU.setEnabled(isEnabled());
        txt_usuarioGU.setEnabled(isEnabled());
        psw_claveGU.setEnabled(isEnabled());
        cmb_nivelGU.setEnabled(isEnabled());

        btn_nuevoGU.setEnabled(!isEnabled());
        btn_editarGU.setEnabled(!isEnabled());
        btn_cancelarGU.setEnabled(isEnabled());
        btn_guardarGU.setEnabled(isEnabled());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_encabezadoGU = new javax.swing.JPanel();
        lbl_tituloGU = new javax.swing.JLabel();
        pnl_derechoGU = new javax.swing.JPanel();
        pnl_pieGU = new javax.swing.JPanel();
        btn_nuevoGU = new javax.swing.JButton();
        btn_editarGU = new javax.swing.JButton();
        btn_cancelarGU = new javax.swing.JButton();
        btn_guardarGU = new javax.swing.JButton();
        btn_salirGU = new javax.swing.JButton();
        pnl_izquierdoGU = new javax.swing.JPanel();
        pnl_centralGU = new javax.swing.JPanel();
        pnl_encabezadoCentralGU = new javax.swing.JPanel();
        lbl_buscarPorUsuarioGU = new javax.swing.JLabel();
        txt_buscarUsuarioPorNombreUsuarioGU = new javax.swing.JTextField();
        pnl_formularioGU = new javax.swing.JPanel();
        lbl_codigoGU = new javax.swing.JLabel();
        txt_codigoGU = new javax.swing.JTextField();
        lbl_apellidoGU = new javax.swing.JLabel();
        txt_apellidoGU = new javax.swing.JTextField();
        lbl_nombreGU = new javax.swing.JLabel();
        txt_nombreGU = new javax.swing.JTextField();
        lbl_nombreUsuarioGU = new javax.swing.JLabel();
        txt_usuarioGU = new javax.swing.JTextField();
        lbl_claveGU = new javax.swing.JLabel();
        psw_claveGU = new javax.swing.JPasswordField();
        lbl_nivelGU = new javax.swing.JLabel();
        cmb_nivelGU = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_listadoUsuariosGU = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion Usuarios");

        pnl_encabezadoGU.setPreferredSize(new java.awt.Dimension(651, 50));
        pnl_encabezadoGU.setLayout(new java.awt.BorderLayout());

        lbl_tituloGU.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloGU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloGU.setText("Gestion de Usuarios");
        pnl_encabezadoGU.add(lbl_tituloGU, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_encabezadoGU, java.awt.BorderLayout.NORTH);

        pnl_derechoGU.setPreferredSize(new java.awt.Dimension(50, 183));

        javax.swing.GroupLayout pnl_derechoGULayout = new javax.swing.GroupLayout(pnl_derechoGU);
        pnl_derechoGU.setLayout(pnl_derechoGULayout);
        pnl_derechoGULayout.setHorizontalGroup(
            pnl_derechoGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_derechoGULayout.setVerticalGroup(
            pnl_derechoGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoGU, java.awt.BorderLayout.EAST);

        pnl_pieGU.setPreferredSize(new java.awt.Dimension(50, 50));
        pnl_pieGU.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btn_nuevoGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nuevoGU.setText("Nuevo");
        btn_nuevoGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGUActionPerformed(evt);
            }
        });
        pnl_pieGU.add(btn_nuevoGU);

        btn_editarGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_editarGU.setText("Editar");
        btn_editarGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarGUActionPerformed(evt);
            }
        });
        pnl_pieGU.add(btn_editarGU);

        btn_cancelarGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarGU.setText("Cancelar");
        btn_cancelarGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarGUActionPerformed(evt);
            }
        });
        pnl_pieGU.add(btn_cancelarGU);

        btn_guardarGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarGU.setText("Guardar");
        btn_guardarGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGUActionPerformed(evt);
            }
        });
        pnl_pieGU.add(btn_guardarGU);

        btn_salirGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_salirGU.setText("Salir");
        btn_salirGU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirGUActionPerformed(evt);
            }
        });
        pnl_pieGU.add(btn_salirGU);

        getContentPane().add(pnl_pieGU, java.awt.BorderLayout.SOUTH);

        pnl_izquierdoGU.setPreferredSize(new java.awt.Dimension(50, 183));

        javax.swing.GroupLayout pnl_izquierdoGULayout = new javax.swing.GroupLayout(pnl_izquierdoGU);
        pnl_izquierdoGU.setLayout(pnl_izquierdoGULayout);
        pnl_izquierdoGULayout.setHorizontalGroup(
            pnl_izquierdoGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_izquierdoGULayout.setVerticalGroup(
            pnl_izquierdoGULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoGU, java.awt.BorderLayout.WEST);

        pnl_centralGU.setLayout(new java.awt.BorderLayout());

        pnl_encabezadoCentralGU.setPreferredSize(new java.awt.Dimension(785, 50));
        pnl_encabezadoCentralGU.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 15));

        lbl_buscarPorUsuarioGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscarPorUsuarioGU.setText("Buscar por Usuario: ");
        pnl_encabezadoCentralGU.add(lbl_buscarPorUsuarioGU);

        txt_buscarUsuarioPorNombreUsuarioGU.setColumns(10);
        txt_buscarUsuarioPorNombreUsuarioGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_buscarUsuarioPorNombreUsuarioGU.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_buscarUsuarioPorNombreUsuarioGU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarUsuarioPorNombreUsuarioGUKeyReleased(evt);
            }
        });
        pnl_encabezadoCentralGU.add(txt_buscarUsuarioPorNombreUsuarioGU);

        pnl_centralGU.add(pnl_encabezadoCentralGU, java.awt.BorderLayout.NORTH);

        pnl_formularioGU.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        lbl_codigoGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoGU.setText("Codigo: ");
        pnl_formularioGU.add(lbl_codigoGU);

        txt_codigoGU.setColumns(2);
        txt_codigoGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGU.add(txt_codigoGU);

        lbl_apellidoGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_apellidoGU.setText("Apellido: ");
        pnl_formularioGU.add(lbl_apellidoGU);

        txt_apellidoGU.setColumns(10);
        txt_apellidoGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGU.add(txt_apellidoGU);

        lbl_nombreGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreGU.setText("Nombre: ");
        pnl_formularioGU.add(lbl_nombreGU);

        txt_nombreGU.setColumns(10);
        txt_nombreGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGU.add(txt_nombreGU);

        lbl_nombreUsuarioGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreUsuarioGU.setText("Usuario:");
        pnl_formularioGU.add(lbl_nombreUsuarioGU);

        txt_usuarioGU.setColumns(10);
        txt_usuarioGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_formularioGU.add(txt_usuarioGU);

        lbl_claveGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_claveGU.setText("Clave: ");
        pnl_formularioGU.add(lbl_claveGU);

        psw_claveGU.setColumns(10);
        psw_claveGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        psw_claveGU.setText("jPasswordField1");
        pnl_formularioGU.add(psw_claveGU);

        lbl_nivelGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nivelGU.setText("Nivel: ");
        pnl_formularioGU.add(lbl_nivelGU);

        cmb_nivelGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_nivelGU.setPreferredSize(new java.awt.Dimension(150, 25));
        pnl_formularioGU.add(cmb_nivelGU);

        pnl_centralGU.add(pnl_formularioGU, java.awt.BorderLayout.SOUTH);

        tb_listadoUsuariosGU.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tb_listadoUsuariosGU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_listadoUsuariosGU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listadoUsuariosGUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_listadoUsuariosGU);

        pnl_centralGU.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_centralGU, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGUActionPerformed

        this.cambiarEstado();
        tb_listadoUsuariosGU.clearSelection();

    }//GEN-LAST:event_btn_nuevoGUActionPerformed

    private void tb_listadoUsuariosGUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listadoUsuariosGUMouseClicked


    }//GEN-LAST:event_tb_listadoUsuariosGUMouseClicked

    private void btn_guardarGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGUActionPerformed
        try {

            if (!txt_apellidoGU.getText().trim().isEmpty() && !txt_nombreGU.getText().trim().isEmpty()
                    && !txt_usuarioGU.getText().trim().isEmpty() && cmb_nivelGU.getSelectedItem() != null && cmb_nivelGU.getSelectedItem() != "[SELECCIONAR]"
                    && !psw_claveGU.getText().trim().isEmpty()) {

                String nombre = txt_nombreGU.getText().trim();
                String apellido = txt_apellidoGU.getText().trim();
                String nombreUsuario = txt_usuarioGU.getText().trim();
                String clave = psw_claveGU.getText().trim();
                NivelDeUsuario nivel = (NivelDeUsuario) cmb_nivelGU.getSelectedItem();

                if (txt_codigoGU.getText().isEmpty()) {
                    String registradoPor = this.usuario.getNombreUsuario();
                    Usuario usuario = new Usuario(nombreUsuario, clave, nivel, apellido, nombre, registradoPor);
                    this.cp.getControladoraLogueo().registarUsuario(usuario);
                    JOptionPane.showMessageDialog(null, "Creado con Exito", "Gestion de Usuarios", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    Integer codigo = Integer.valueOf(txt_codigoGU.getText());
                    Usuario usuario = this.cp.getControladoraLogueo().buscarUsuarioPorCodigo(codigo);
                    usuario.setApellido(apellido);
                    usuario.setNombre(nombre);
                    usuario.setNombreUsuario(nombreUsuario);
                    usuario.setClave(clave);
                    usuario.setNivel(nivel);
                    usuario.setUltimaModificacionPor(this.usuario.getNombreUsuario());
                    this.cp.getControladoraLogueo().modificarUsuario(usuario);

                    JOptionPane.showMessageDialog(null, "Editado con Exito", "Gestion de Usuarios", JOptionPane.INFORMATION_MESSAGE);
                }
                this.estadoInicial();
            } else {
                throw new Exception("Todos los campos son obligatorios");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Gestion de Usuarios", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btn_guardarGUActionPerformed

    private void btn_editarGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarGUActionPerformed
        if (tb_listadoUsuariosGU.getSelectedRow() > -1 && tb_listadoUsuariosGU.getSelectedRowCount() == 1) {

            Integer seleccionado = (Integer) tb_listadoUsuariosGU.getValueAt(tb_listadoUsuariosGU.getSelectedRow(), 0);
            Usuario usuarioSeleccionado = this.cp.getControladoraLogueo().buscarUsuarioPorCodigo(seleccionado);

            if (usuarioSeleccionado != null) {
                this.cambiarEstado();
                txt_codigoGU.setText(String.valueOf(usuarioSeleccionado.getCodigo()));
                txt_nombreGU.setText(usuarioSeleccionado.getNombre());
                txt_apellidoGU.setText(usuarioSeleccionado.getApellido());
                txt_usuarioGU.setText(usuarioSeleccionado.getNombreUsuario());
                psw_claveGU.setText(usuarioSeleccionado.getClave());
                cmb_nivelGU.setSelectedItem(usuarioSeleccionado.getNivel());

            }

            
            tb_listadoUsuariosGU.clearSelection();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario", "Gestion de Usuarios", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarGUActionPerformed

    private void btn_cancelarGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarGUActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_btn_cancelarGUActionPerformed

    private void btn_salirGUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirGUActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirGUActionPerformed

    private void txt_buscarUsuarioPorNombreUsuarioGUKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarUsuarioPorNombreUsuarioGUKeyReleased
        if (!txt_buscarUsuarioPorNombreUsuarioGU.getText().trim().isEmpty()) {
            String nombre = txt_buscarUsuarioPorNombreUsuarioGU.getText().trim();
            cargarTabla(this.cp.getControladoraLogueo().filtrarXnombreUsuario(nombre));
        }else{
            cargarTabla(this.cp.getControladoraLogueo().listarUsuario());
        }
    }//GEN-LAST:event_txt_buscarUsuarioPorNombreUsuarioGUKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarGU;
    private javax.swing.JButton btn_editarGU;
    private javax.swing.JButton btn_guardarGU;
    private javax.swing.JButton btn_nuevoGU;
    private javax.swing.JButton btn_salirGU;
    private javax.swing.JComboBox cmb_nivelGU;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_apellidoGU;
    private javax.swing.JLabel lbl_buscarPorUsuarioGU;
    private javax.swing.JLabel lbl_claveGU;
    private javax.swing.JLabel lbl_codigoGU;
    private javax.swing.JLabel lbl_nivelGU;
    private javax.swing.JLabel lbl_nombreGU;
    private javax.swing.JLabel lbl_nombreUsuarioGU;
    private javax.swing.JLabel lbl_tituloGU;
    private javax.swing.JPanel pnl_centralGU;
    private javax.swing.JPanel pnl_derechoGU;
    private javax.swing.JPanel pnl_encabezadoCentralGU;
    private javax.swing.JPanel pnl_encabezadoGU;
    private javax.swing.JPanel pnl_formularioGU;
    private javax.swing.JPanel pnl_izquierdoGU;
    private javax.swing.JPanel pnl_pieGU;
    private javax.swing.JPasswordField psw_claveGU;
    private javax.swing.JTable tb_listadoUsuariosGU;
    private javax.swing.JTextField txt_apellidoGU;
    private javax.swing.JTextField txt_buscarUsuarioPorNombreUsuarioGU;
    private javax.swing.JTextField txt_codigoGU;
    private javax.swing.JTextField txt_nombreGU;
    private javax.swing.JTextField txt_usuarioGU;
    // End of variables declaration//GEN-END:variables
}
