/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Color;
import java.awt.Font;
import java.beans.PropertyVetoException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import modelo.Localidad;
import modelo.Provincia;
import modelo.Usuario;
import modelo.Utilidades;

/**
 *
 * @author EcobarM
 */
public class gestionLocalidades extends javax.swing.JInternalFrame {
    
    private ControladoraPrincipal cp;
    private JDesktopPane dskp_principalVP;
    private Usuario usuario;

    /**
     * Creates new form gestionLocalidades
     */
    public gestionLocalidades(ControladoraPrincipal cp, JDesktopPane dskp_principalVP, Usuario usuario) {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.cp = cp;
        this.dskp_principalVP = dskp_principalVP;
        this.usuario = usuario;
        this.estadoInicial();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_encabezadoGL = new javax.swing.JPanel();
        lbl_tituloGL = new javax.swing.JLabel();
        pnl_pieGL = new javax.swing.JPanel();
        btn_nuevoGL = new javax.swing.JButton();
        btn_editarGL = new javax.swing.JButton();
        btn_cancelarGL = new javax.swing.JButton();
        btn_guardarGL = new javax.swing.JButton();
        btn_salirGL = new javax.swing.JButton();
        pnl_derechoGL = new javax.swing.JPanel();
        pnl_izquierdoGL = new javax.swing.JPanel();
        pnl_centralGL = new javax.swing.JPanel();
        pnl_encabezadoCentralGL = new javax.swing.JPanel();
        lbl_buscarPorProvinciaGL = new javax.swing.JLabel();
        cmb_buscarLocalidadesPorProvinciasGL = new javax.swing.JComboBox();
        pnl_formularioCentralGL = new javax.swing.JPanel();
        lbl_codigoGL = new javax.swing.JLabel();
        txt_codigoGL = new javax.swing.JTextField();
        lbl_NombreGL = new javax.swing.JLabel();
        txt_nombreGL = new javax.swing.JTextField();
        lbl_provinciaGL = new javax.swing.JLabel();
        cmb_provinciaGL = new javax.swing.JComboBox();
        pnl_derechoCentralGL = new javax.swing.JPanel();
        pnl_izquierdoCentralGL = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_listadoLocalidadGL = new javax.swing.JTable();

        setBorder(null);
        setTitle("Gestion Localidades");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnl_encabezadoGL.setPreferredSize(new java.awt.Dimension(704, 50));
        pnl_encabezadoGL.setLayout(new java.awt.BorderLayout());

        lbl_tituloGL.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloGL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloGL.setText("Gestion de Localidades");
        pnl_encabezadoGL.add(lbl_tituloGL, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_encabezadoGL, java.awt.BorderLayout.NORTH);

        pnl_pieGL.setPreferredSize(new java.awt.Dimension(704, 50));
        pnl_pieGL.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btn_nuevoGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_nuevoGL.setText("Nuevo");
        btn_nuevoGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGLActionPerformed(evt);
            }
        });
        pnl_pieGL.add(btn_nuevoGL);

        btn_editarGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_editarGL.setText("Editar");
        btn_editarGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarGLActionPerformed(evt);
            }
        });
        pnl_pieGL.add(btn_editarGL);

        btn_cancelarGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_cancelarGL.setText("Cancelar");
        btn_cancelarGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarGLActionPerformed(evt);
            }
        });
        pnl_pieGL.add(btn_cancelarGL);

        btn_guardarGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarGL.setText("Guardar");
        btn_guardarGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarGLActionPerformed(evt);
            }
        });
        pnl_pieGL.add(btn_guardarGL);

        btn_salirGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_salirGL.setText("Salir");
        btn_salirGL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirGLActionPerformed(evt);
            }
        });
        pnl_pieGL.add(btn_salirGL);

        getContentPane().add(pnl_pieGL, java.awt.BorderLayout.SOUTH);

        pnl_derechoGL.setPreferredSize(new java.awt.Dimension(50, 199));

        javax.swing.GroupLayout pnl_derechoGLLayout = new javax.swing.GroupLayout(pnl_derechoGL);
        pnl_derechoGL.setLayout(pnl_derechoGLLayout);
        pnl_derechoGLLayout.setHorizontalGroup(
            pnl_derechoGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_derechoGLLayout.setVerticalGroup(
            pnl_derechoGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoGL, java.awt.BorderLayout.EAST);

        pnl_izquierdoGL.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout pnl_izquierdoGLLayout = new javax.swing.GroupLayout(pnl_izquierdoGL);
        pnl_izquierdoGL.setLayout(pnl_izquierdoGLLayout);
        pnl_izquierdoGLLayout.setHorizontalGroup(
            pnl_izquierdoGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_izquierdoGLLayout.setVerticalGroup(
            pnl_izquierdoGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoGL, java.awt.BorderLayout.WEST);

        pnl_centralGL.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15);
        flowLayout1.setAlignOnBaseline(true);
        pnl_encabezadoCentralGL.setLayout(flowLayout1);

        lbl_buscarPorProvinciaGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_buscarPorProvinciaGL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_buscarPorProvinciaGL.setText("Buscar por Provincia: ");
        lbl_buscarPorProvinciaGL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_encabezadoCentralGL.add(lbl_buscarPorProvinciaGL);

        cmb_buscarLocalidadesPorProvinciasGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_buscarLocalidadesPorProvinciasGL.setPreferredSize(new java.awt.Dimension(180, 25));
        cmb_buscarLocalidadesPorProvinciasGL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_buscarLocalidadesPorProvinciasGLItemStateChanged(evt);
            }
        });
        cmb_buscarLocalidadesPorProvinciasGL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_buscarLocalidadesPorProvinciasGLMouseClicked(evt);
            }
        });
        pnl_encabezadoCentralGL.add(cmb_buscarLocalidadesPorProvinciasGL);

        pnl_centralGL.add(pnl_encabezadoCentralGL, java.awt.BorderLayout.NORTH);

        pnl_formularioCentralGL.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 30));

        lbl_codigoGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoGL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codigoGL.setText("Codigo: ");
        lbl_codigoGL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnl_formularioCentralGL.add(lbl_codigoGL);

        txt_codigoGL.setColumns(2);
        txt_codigoGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_codigoGL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pnl_formularioCentralGL.add(txt_codigoGL);

        lbl_NombreGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_NombreGL.setText("Nombre: ");
        pnl_formularioCentralGL.add(lbl_NombreGL);

        txt_nombreGL.setColumns(10);
        txt_nombreGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txt_nombreGL.setPreferredSize(new java.awt.Dimension(150, 25));
        txt_nombreGL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreGLKeyTyped(evt);
            }
        });
        pnl_formularioCentralGL.add(txt_nombreGL);

        lbl_provinciaGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_provinciaGL.setText("Provincia: ");
        pnl_formularioCentralGL.add(lbl_provinciaGL);

        cmb_provinciaGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cmb_provinciaGL.setMaximumRowCount(10);
        cmb_provinciaGL.setPreferredSize(new java.awt.Dimension(150, 25));
        pnl_formularioCentralGL.add(cmb_provinciaGL);

        pnl_centralGL.add(pnl_formularioCentralGL, java.awt.BorderLayout.SOUTH);

        pnl_derechoCentralGL.setPreferredSize(new java.awt.Dimension(100, 0));

        javax.swing.GroupLayout pnl_derechoCentralGLLayout = new javax.swing.GroupLayout(pnl_derechoCentralGL);
        pnl_derechoCentralGL.setLayout(pnl_derechoCentralGLLayout);
        pnl_derechoCentralGLLayout.setHorizontalGroup(
            pnl_derechoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_derechoCentralGLLayout.setVerticalGroup(
            pnl_derechoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_centralGL.add(pnl_derechoCentralGL, java.awt.BorderLayout.WEST);

        pnl_izquierdoCentralGL.setPreferredSize(new java.awt.Dimension(100, 180));

        javax.swing.GroupLayout pnl_izquierdoCentralGLLayout = new javax.swing.GroupLayout(pnl_izquierdoCentralGL);
        pnl_izquierdoCentralGL.setLayout(pnl_izquierdoCentralGLLayout);
        pnl_izquierdoCentralGLLayout.setHorizontalGroup(
            pnl_izquierdoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnl_izquierdoCentralGLLayout.setVerticalGroup(
            pnl_izquierdoCentralGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        pnl_centralGL.add(pnl_izquierdoCentralGL, java.awt.BorderLayout.EAST);

        tb_listadoLocalidadGL.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tb_listadoLocalidadGL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_listadoLocalidadGL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listadoLocalidadGLMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_listadoLocalidadGL);

        pnl_centralGL.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_centralGL, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarGLActionPerformed
        
        try {
            if (!txt_nombreGL.getText().trim().isEmpty() && cmb_provinciaGL.getSelectedItem() != "[SELECCIONAR]" && cmb_provinciaGL.getSelectedItem() != null) {
                String nombre = txt_nombreGL.getText().trim();
                Provincia provincia = (Provincia) cmb_provinciaGL.getSelectedItem();
                if (txt_codigoGL.getText().trim().isEmpty()) {
                    
                    Localidad localidad = new Localidad(nombre, provincia);
                    this.cp.getControladoraCliente().registrarLocalidad(localidad);
                    JOptionPane.showMessageDialog(null, "Creado con Exito", "Gestion de Localidades", JOptionPane.INFORMATION_MESSAGE);
                    
                } else {
                    Integer codigo = Integer.valueOf(txt_codigoGL.getText());
                    
                    Localidad localidad = this.cp.getControladoraCliente().buscarLocalidadPorCodigo(codigo);
                    localidad.setNombre(nombre);
                    localidad.setProvincia(provincia);
                    
                    this.cp.getControladoraCliente().modificarLocalidad(localidad);
                    
                    JOptionPane.showMessageDialog(null, "Editado con Exito", "Gestion de Localidades", JOptionPane.INFORMATION_MESSAGE);
                    
                }
                this.estadoInicial();
            } else {
                
                throw new Exception("Todos los campos son obligatorios");
                
            }
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Gestion de Localidades", JOptionPane.WARNING_MESSAGE);
            
        }
        

    }//GEN-LAST:event_btn_guardarGLActionPerformed

    private void btn_salirGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirGLActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirGLActionPerformed

    private void cmb_buscarLocalidadesPorProvinciasGLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_buscarLocalidadesPorProvinciasGLItemStateChanged
        if (cmb_buscarLocalidadesPorProvinciasGL.getSelectedItem() != "[SELECCIONAR]" && cmb_buscarLocalidadesPorProvinciasGL.getSelectedItem() != null) {
            Provincia provincia = (Provincia) cmb_buscarLocalidadesPorProvinciasGL.getSelectedItem();
            cargarTabla(this.cp.getControladoraCliente().filtrarLocalidadPorProvincia(provincia));
        } else {
            cargarTabla(this.cp.getControladoraCliente().listarLocalidades());
        }
        

    }//GEN-LAST:event_cmb_buscarLocalidadesPorProvinciasGLItemStateChanged

    private void btn_nuevoGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGLActionPerformed
        this.cambiarEstado();
        tb_listadoLocalidadGL.clearSelection();

    }//GEN-LAST:event_btn_nuevoGLActionPerformed

    private void btn_editarGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarGLActionPerformed
        if (tb_listadoLocalidadGL.getSelectedRow() > -1 && tb_listadoLocalidadGL.getSelectedRowCount() == 1) {
            Integer seleccionado = (Integer) tb_listadoLocalidadGL.getValueAt(tb_listadoLocalidadGL.getSelectedRow(), 0);
            Localidad localidadSeleccionado = this.cp.getControladoraCliente().buscarLocalidadPorCodigo(seleccionado);
            
            if (localidadSeleccionado != null) {
                this.cambiarEstado();
                
                txt_codigoGL.setText(String.valueOf(localidadSeleccionado.getCodigo()));
                txt_nombreGL.setText(localidadSeleccionado.getNombre());
                cmb_provinciaGL.setSelectedItem(localidadSeleccionado.getProvincia());
                
            }
            
            tb_listadoLocalidadGL.clearSelection();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un localidad", "Gestion de Localidades", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btn_editarGLActionPerformed

    private void btn_cancelarGLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarGLActionPerformed
        this.estadoInicial();
    }//GEN-LAST:event_btn_cancelarGLActionPerformed

    private void cmb_buscarLocalidadesPorProvinciasGLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_buscarLocalidadesPorProvinciasGLMouseClicked

    }//GEN-LAST:event_cmb_buscarLocalidadesPorProvinciasGLMouseClicked

    private void tb_listadoLocalidadGLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listadoLocalidadGLMouseClicked

    }//GEN-LAST:event_tb_listadoLocalidadGLMouseClicked

    private void txt_nombreGLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreGLKeyTyped
        Utilidades.DelimitarLetras(evt);
    }//GEN-LAST:event_txt_nombreGLKeyTyped
    
    public void estadoInicial() {
        btn_nuevoGL.setEnabled(isEnabled());
        btn_editarGL.setEnabled(isEnabled());
        btn_cancelarGL.setEnabled(!isEnabled());
        btn_guardarGL.setEnabled(!isEnabled());
        btn_salirGL.setEnabled(isEnabled());
        
        txt_codigoGL.setEnabled(!isEnabled());
        txt_nombreGL.setEnabled(!isEnabled());
        
        cmb_provinciaGL.setEnabled(!isEnabled());
        
        cmb_buscarLocalidadesPorProvinciasGL.setEnabled(isEnabled());
        
        tb_listadoLocalidadGL.setEnabled(isEnabled());
        UIManager.put("ComboBox.disabledBackground", new Color(212, 212, 210));
        UIManager.put("ComboBox.disabledForeground", Color.BLACK);
        
        txt_codigoGL.setText("");
        txt_nombreGL.setText("");
        
        txt_codigoGL.setBackground(Color.white);
        txt_nombreGL.setBackground(Color.white);
        cmb_provinciaGL.setBackground(Color.WHITE);
        
        txt_codigoGL.setDisabledTextColor(Color.BLACK);
        txt_nombreGL.setDisabledTextColor(Color.BLACK);
        
        cargarTabla(this.cp.getControladoraCliente().listarLocalidades());
        Utilidades.cargarCombo(this.cp.getControladoraCliente().listarProvincias(), cmb_provinciaGL);
        Utilidades.cargarCombo(this.cp.getControladoraCliente().listarProvincias(), cmb_buscarLocalidadesPorProvinciasGL);
        
    }
    
    public void cambiarEstado() {
        
        Utilidades.cargarCombo(this.cp.getControladoraCliente().listarProvincias(), cmb_provinciaGL);
        Utilidades.cargarCombo(this.cp.getControladoraCliente().listarProvincias(), cmb_buscarLocalidadesPorProvinciasGL);
        
        tb_listadoLocalidadGL.setEnabled(!isEnabled());
        btn_nuevoGL.setEnabled(!isEnabled());
        btn_editarGL.setEnabled(!isEnabled());
        btn_cancelarGL.setEnabled(isEnabled());
        btn_guardarGL.setEnabled(isEnabled());
        txt_nombreGL.setEnabled(isEnabled());
        cmb_provinciaGL.setEnabled(isEnabled());
        
    }
    
    public void cargarTabla(List<Localidad> localidades) {
        DefaultTableModel tbCarga = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        if (!localidades.isEmpty()) {
            String Cabecera[] = {"Codigo", "Nombre", "Provincia"};
            tbCarga.setColumnIdentifiers(Cabecera);
            Object fila[] = new Object[tbCarga.getColumnCount()];
            tb_listadoLocalidadGL.getTableHeader().setFont(new Font("Century Ghotic", Font.BOLD, 14));
            for (Localidad l : localidades) {
                fila[0] = l.getCodigo();
                fila[1] = l.getNombre();
                fila[2] = l.getProvincia();
                tbCarga.addRow(fila);
            }
            
        }
        tb_listadoLocalidadGL.setModel(tbCarga);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelarGL;
    private javax.swing.JButton btn_editarGL;
    private javax.swing.JButton btn_guardarGL;
    private javax.swing.JButton btn_nuevoGL;
    private javax.swing.JButton btn_salirGL;
    private javax.swing.JComboBox cmb_buscarLocalidadesPorProvinciasGL;
    private javax.swing.JComboBox cmb_provinciaGL;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_NombreGL;
    private javax.swing.JLabel lbl_buscarPorProvinciaGL;
    private javax.swing.JLabel lbl_codigoGL;
    private javax.swing.JLabel lbl_provinciaGL;
    private javax.swing.JLabel lbl_tituloGL;
    private javax.swing.JPanel pnl_centralGL;
    private javax.swing.JPanel pnl_derechoCentralGL;
    private javax.swing.JPanel pnl_derechoGL;
    private javax.swing.JPanel pnl_encabezadoCentralGL;
    private javax.swing.JPanel pnl_encabezadoGL;
    private javax.swing.JPanel pnl_formularioCentralGL;
    private javax.swing.JPanel pnl_izquierdoCentralGL;
    private javax.swing.JPanel pnl_izquierdoGL;
    private javax.swing.JPanel pnl_pieGL;
    private javax.swing.JTable tb_listadoLocalidadGL;
    private javax.swing.JTextField txt_codigoGL;
    private javax.swing.JTextField txt_nombreGL;
    // End of variables declaration//GEN-END:variables
}
