/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.ControladoraPrincipal;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.EstadoServicio;
import modelo.NivelDeUsuario;
import modelo.Permiso;
import modelo.TipoEquipo;
import modelo.Usuario;

/**
 *
 * @author EcobarM
 */
public class Registrarme extends javax.swing.JFrame {

    /**
     * Creates new form Registrarme
     */
    private ControladoraPrincipal cp;
    private boolean mostrar = false;

    public Registrarme(ControladoraPrincipal cp) {
        this.cp = cp;
        this.setSize(700, 500);
        this.setResizable(false);
        this.setTitle("Registrarme en Tecnicamente");
        this.setLocationRelativeTo(null);
        this.setIconImage(getIconImage());

        initComponents();

//        pnl_centralRegistrarme.setBackground(new Color(235, 135, 0));
//        pnl_derechoRegistrarme.setBackground(new Color(235, 135, 0));
//        pnl_encabezadoRegistrarme.setBackground(new Color(235, 135, 0));
//        pnl_izquierdoRegistrarme.setBackground(new Color(235, 135, 0));
//        pnl_formularioRegistrarme.setBackground(new Color(235, 135, 0));
//        pnl_pieRegistrarme.setBackground(new Color(235, 135, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_pieRegistrarme = new javax.swing.JPanel();
        btn_guardarRegistarme = new javax.swing.JButton();
        pnl_centralRegistrarme = new javax.swing.JPanel();
        pnl_formularioRegistrarme = new javax.swing.JPanel();
        pnl_datosPersonalesRegistrarme = new javax.swing.JPanel();
        lbl_apellidoRegistrarme = new javax.swing.JLabel();
        txt_apellidoRegistrarme = new javax.swing.JTextField();
        lbl_nombreRegistrarme = new javax.swing.JLabel();
        txt_nombreRegistrarme = new javax.swing.JTextField();
        pnl_usuariosRegistrarme = new javax.swing.JPanel();
        lbl_nombreUsuarioRegistrarme = new javax.swing.JLabel();
        txt_usuarioRegistrarme = new javax.swing.JTextField();
        lbl_claveRegistrarme = new javax.swing.JLabel();
        psw_claveRegistrarme = new javax.swing.JPasswordField();
        lbl_mostrarClaveRegistrarme = new javax.swing.JLabel();
        pnl_derechoRegistrarme = new javax.swing.JPanel();
        pnl_izquierdoRegistrarme = new javax.swing.JPanel();
        pnl_encabezadoRegistrarme = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 300));
        setName("frm_registrarme"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 300));

        pnl_pieRegistrarme.setPreferredSize(new java.awt.Dimension(100, 50));
        pnl_pieRegistrarme.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        btn_guardarRegistarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_guardarRegistarme.setText("Guardar");
        btn_guardarRegistarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarRegistarmeActionPerformed(evt);
            }
        });
        pnl_pieRegistrarme.add(btn_guardarRegistarme);

        getContentPane().add(pnl_pieRegistrarme, java.awt.BorderLayout.SOUTH);

        pnl_centralRegistrarme.setPreferredSize(new java.awt.Dimension(500, 300));
        pnl_centralRegistrarme.setLayout(new java.awt.BorderLayout());

        pnl_formularioRegistrarme.setPreferredSize(new java.awt.Dimension(700, 200));
        pnl_formularioRegistrarme.setLayout(new java.awt.GridLayout(2, 0));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        pnl_datosPersonalesRegistrarme.setLayout(flowLayout1);

        lbl_apellidoRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_apellidoRegistrarme.setText("Apellido:");
        pnl_datosPersonalesRegistrarme.add(lbl_apellidoRegistrarme);

        txt_apellidoRegistrarme.setColumns(15);
        txt_apellidoRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_datosPersonalesRegistrarme.add(txt_apellidoRegistrarme);

        lbl_nombreRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreRegistrarme.setText("Nombre: ");
        pnl_datosPersonalesRegistrarme.add(lbl_nombreRegistrarme);

        txt_nombreRegistrarme.setColumns(15);
        txt_nombreRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_datosPersonalesRegistrarme.add(txt_nombreRegistrarme);

        pnl_formularioRegistrarme.add(pnl_datosPersonalesRegistrarme);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        pnl_usuariosRegistrarme.setLayout(flowLayout2);

        lbl_nombreUsuarioRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombreUsuarioRegistrarme.setText(" Usuario:");
        pnl_usuariosRegistrarme.add(lbl_nombreUsuarioRegistrarme);

        txt_usuarioRegistrarme.setColumns(15);
        txt_usuarioRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_usuariosRegistrarme.add(txt_usuarioRegistrarme);

        lbl_claveRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_claveRegistrarme.setText("Clave:");
        pnl_usuariosRegistrarme.add(lbl_claveRegistrarme);

        psw_claveRegistrarme.setColumns(15);
        psw_claveRegistrarme.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pnl_usuariosRegistrarme.add(psw_claveRegistrarme);

        lbl_mostrarClaveRegistrarme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_mostrarClaveRegistrarme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/invisible-50.png"))); // NOI18N
        lbl_mostrarClaveRegistrarme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_mostrarClaveRegistrarme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mostrarClaveRegistrarmeMouseClicked(evt);
            }
        });
        pnl_usuariosRegistrarme.add(lbl_mostrarClaveRegistrarme);

        pnl_formularioRegistrarme.add(pnl_usuariosRegistrarme);

        pnl_centralRegistrarme.add(pnl_formularioRegistrarme, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_centralRegistrarme, java.awt.BorderLayout.CENTER);

        pnl_derechoRegistrarme.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout pnl_derechoRegistrarmeLayout = new javax.swing.GroupLayout(pnl_derechoRegistrarme);
        pnl_derechoRegistrarme.setLayout(pnl_derechoRegistrarmeLayout);
        pnl_derechoRegistrarmeLayout.setHorizontalGroup(
            pnl_derechoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_derechoRegistrarmeLayout.setVerticalGroup(
            pnl_derechoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_derechoRegistrarme, java.awt.BorderLayout.EAST);

        pnl_izquierdoRegistrarme.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout pnl_izquierdoRegistrarmeLayout = new javax.swing.GroupLayout(pnl_izquierdoRegistrarme);
        pnl_izquierdoRegistrarme.setLayout(pnl_izquierdoRegistrarmeLayout);
        pnl_izquierdoRegistrarmeLayout.setHorizontalGroup(
            pnl_izquierdoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        pnl_izquierdoRegistrarmeLayout.setVerticalGroup(
            pnl_izquierdoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_izquierdoRegistrarme, java.awt.BorderLayout.WEST);

        pnl_encabezadoRegistrarme.setPreferredSize(new java.awt.Dimension(100, 50));

        javax.swing.GroupLayout pnl_encabezadoRegistrarmeLayout = new javax.swing.GroupLayout(pnl_encabezadoRegistrarme);
        pnl_encabezadoRegistrarme.setLayout(pnl_encabezadoRegistrarmeLayout);
        pnl_encabezadoRegistrarmeLayout.setHorizontalGroup(
            pnl_encabezadoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 908, Short.MAX_VALUE)
        );
        pnl_encabezadoRegistrarmeLayout.setVerticalGroup(
            pnl_encabezadoRegistrarmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_encabezadoRegistrarme, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarRegistarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarRegistarmeActionPerformed

        boolean gestionServicioTecnico = true;
        boolean gestionUsuario = true;
        boolean gestionCliente = true;
        boolean gestionCompra = true;
        boolean gestionVenta = true;
        boolean gestionInformes = true;
        boolean gestionParametro = true;
        boolean gestionEquipo = true;
        boolean gestionProducto = true;
        boolean gestionServicio = true;

        try {

            if (!txt_usuarioRegistrarme.getText().trim().isEmpty() && !txt_apellidoRegistrarme.getText().trim().isEmpty() && !txt_nombreRegistrarme.getText().trim().isEmpty() && !psw_claveRegistrarme.getText().trim().isEmpty()) {

                String nombreUsuario = txt_usuarioRegistrarme.getText().trim();
                String clave = psw_claveRegistrarme.getText().trim();
                String apellido = txt_apellidoRegistrarme.getText().trim();
                String nombre = txt_nombreRegistrarme.getText().trim();
                String registradoPor = nombreUsuario;

                Permiso permiso = new Permiso(gestionCompra, gestionVenta, gestionCliente, gestionEquipo, gestionServicioTecnico, gestionServicio, gestionInformes, gestionUsuario, gestionProducto, gestionParametro);
                permiso = this.cp.getControladoraLogueo().registarPermiso(permiso);
                NivelDeUsuario nivel = new NivelDeUsuario("ADMINISTRADOR", permiso);
                nivel = this.cp.getControladoraLogueo().registrarPrimerNivel(nivel);
                Usuario usuario = new Usuario(nombreUsuario, clave, nivel, apellido, nombre, registradoPor);

                this.cp.getControladoraLogueo().registarUsuario(usuario);
                JOptionPane.showMessageDialog(null, "Se registro Correctamente", "Login", JOptionPane.INFORMATION_MESSAGE);

                EstadoServicio estado1 = new EstadoServicio("Pendiente");
                EstadoServicio estado2 = new EstadoServicio("Reparado");
                EstadoServicio estado3 = new EstadoServicio("Entregado");

                TipoEquipo tipo1 = new TipoEquipo("Notebook");
                TipoEquipo tipo2 = new TipoEquipo("Pc Escritorio");
                TipoEquipo tipo3 = new TipoEquipo("Celular");
                TipoEquipo tipo4 = new TipoEquipo("Tablet");
                TipoEquipo tipo5 = new TipoEquipo("Impresora");

                this.cp.getControladoraServicioTecnico().registrarTipoEquipo(tipo1);
                this.cp.getControladoraServicioTecnico().registrarTipoEquipo(tipo2);
                this.cp.getControladoraServicioTecnico().registrarTipoEquipo(tipo3);
                this.cp.getControladoraServicioTecnico().registrarTipoEquipo(tipo4);
                this.cp.getControladoraServicioTecnico().registrarTipoEquipo(tipo5);

                this.cp.getControladoraServicioTecnico().registrarEstadoServicio(estado1);
                this.cp.getControladoraServicioTecnico().registrarEstadoServicio(estado2);
                this.cp.getControladoraServicioTecnico().registrarEstadoServicio(estado3);
                
                this.dispose();

                Login login = new Login(cp);
                login.setVisible(true);

            } else {
                throw new Exception("TODOS LOS CAMPOS SON OBLIGATORIOS");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Login", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btn_guardarRegistarmeActionPerformed

    private void lbl_mostrarClaveRegistrarmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mostrarClaveRegistrarmeMouseClicked
        ImageIcon image = new ImageIcon("src/imagenes/visible-50.png");

        if (mostrar == false) {
            lbl_mostrarClaveRegistrarme.setIcon(image);
            psw_claveRegistrarme.setEchoChar((char) 0);
            mostrar = true;

        } else {
            image = new ImageIcon("src/imagenes/invisible-50.png");
            lbl_mostrarClaveRegistrarme.setIcon(image);
            psw_claveRegistrarme.setEchoChar((char) '\u25cf');
            mostrar = false;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_mostrarClaveRegistrarmeMouseClicked

    @Override
    public Image getIconImage() {
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo-100.png"));
        return retvalue;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarRegistarme;
    private javax.swing.JLabel lbl_apellidoRegistrarme;
    private javax.swing.JLabel lbl_claveRegistrarme;
    private javax.swing.JLabel lbl_mostrarClaveRegistrarme;
    private javax.swing.JLabel lbl_nombreRegistrarme;
    private javax.swing.JLabel lbl_nombreUsuarioRegistrarme;
    private javax.swing.JPanel pnl_centralRegistrarme;
    private javax.swing.JPanel pnl_datosPersonalesRegistrarme;
    private javax.swing.JPanel pnl_derechoRegistrarme;
    private javax.swing.JPanel pnl_encabezadoRegistrarme;
    private javax.swing.JPanel pnl_formularioRegistrarme;
    private javax.swing.JPanel pnl_izquierdoRegistrarme;
    private javax.swing.JPanel pnl_pieRegistrarme;
    private javax.swing.JPanel pnl_usuariosRegistrarme;
    private javax.swing.JPasswordField psw_claveRegistrarme;
    private javax.swing.JTextField txt_apellidoRegistrarme;
    private javax.swing.JTextField txt_nombreRegistrarme;
    private javax.swing.JTextField txt_usuarioRegistrarme;
    // End of variables declaration//GEN-END:variables
}
